os: linux
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="sdl/2.0.4"
    - CONAN_USERNAME="chaosteil"
    - CONAN_CHANNEL="ci"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1

  matrix:
    - CONAN_GCC_VERSIONS=4.6
    - CONAN_GCC_VERSIONS=4.8
    - CONAN_GCC_VERSIONS=4.9 
    - CONAN_GCC_VERSIONS=5.2
    - CONAN_GCC_VERSIONS=5.3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential make cmake autoconf automake xorg-dev libtool libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libgl1-mesa-dev libesd0-dev libdbus-1-dev libudev-dev libgles1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libibus-1.0-dev

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
